name: microsoft-azure-messaging-servicebus-emulator
services:
  emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "./Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "55672:55672"
    environment:
      # SQL_SERVER: sqledge 
      SQL_SERVER: sqledge:1533  #Mounting SQL Edge on a custom port as Dev might have SQLExpress Windows Service Running
      MSSQL_SA_PASSWORD: ""  # Password should be same as what is set for SQL Edge  
      ACCEPT_EULA: "Y"
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqledge:
        container_name: "sqledge"
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        ports:
          # - "1433:1433"
          - "1533:1433"  #Mounting SQL Edge on a custom port as Dev might have SQLExpress Windows Service Running
        networks:
          sb-emulator:
            aliases:
              - "sqledge"
        environment:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "" # To be filled by user as per policy : https://learn.microsoft.com/en-us/sql/relational-databases/security/strong-passwords?view=sql-server-linux-ver16 

networks:
  sb-emulator:

