name: microsoft-azure-servicebus-emulator
services:
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "./Config.json:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment: 
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: ""  # Password should be same as what is set for SQL Edge  
      ACCEPT_EULA: "N"
    depends_on:
      - sqledge
  sqledge:
        container_name: "sqledge"
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        environment:
          ACCEPT_EULA: "N"
          MSSQL_SA_PASSWORD: "" # To be filled by user as per policy : https://learn.microsoft.com/en-us/sql/relational-databases/security/strong-passwords?view=sql-server-linux-ver16
  sample-containerized-app:
    build:
      context: .
      dockerfile: ./Dockerfile
